# Generated by Django 2.2.7 on 2020-02-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buname', models.CharField(max_length=100)),
                ('millname', models.CharField(max_length=100)),
                ('bamt', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='mill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mill_name', models.CharField(max_length=100)),
                ('mill_loc', models.CharField(max_length=100)),
                ('mob', models.IntegerField()),
                ('Email', models.CharField(max_length=100)),
            ],
        ),
    ]
