# Generated by Django 2.2.7 on 2020-02-24 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mill',
            old_name='Email',
            new_name='email',
        ),
    ]
