# Generated by Django 2.2.7 on 2020-02-25 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20200225_0956'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='usersell',
            new_name='usell',
        ),
        migrations.RenameField(
            model_name='usell',
            old_name='typeofwood',
            new_name='type_of_wood',
        ),
    ]
