# Generated by Django 2.2.7 on 2020-02-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_auto_20200225_1134'),
    ]

    operations = [
        migrations.AddField(
            model_name='mill',
            name='uname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
