# Generated by Django 2.2.7 on 2020-03-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0008_auto_20200302_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='uname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
