# Generated by Django 2.2.7 on 2020-03-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_sell_uname'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=100)),
                ('type_of_wood', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
                ('width', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('status', models.CharField(max_length=100)),
            ],
        ),
    ]
