# Generated by Django 2.2.7 on 2020-03-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_auto_20200325_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='uname',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
