# Generated by Django 2.2.7 on 2020-03-26 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0012_booking_uname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='uname',
        ),
    ]
