# Generated by Django 2.2.7 on 2020-03-26 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0013_remove_booking_uname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='length',
            new_name='lenn',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='rate',
            new_name='rat',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='status',
            new_name='stus',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='type_of_wood',
            new_name='type_wd',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='width',
            new_name='wid',
        ),
    ]
