# Generated by Django 2.2.7 on 2020-03-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0015_booking_uname'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mname',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
