# Generated by Django 2.2.7 on 2020-03-26 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0017_auto_20200326_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='mob',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
