# Generated by Django 2.2.7 on 2020-03-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0019_remove_booking_mob'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='mob',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
    ]
