# Generated by Django 2.2.7 on 2020-03-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0020_booking_mob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='mob',
            field=models.CharField(max_length=100),
        ),
    ]
