# Generated by Django 2.2.7 on 2020-04-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0021_auto_20200326_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mill',
            old_name='uname',
            new_name='muname',
        ),
        migrations.AddField(
            model_name='sell',
            name='m_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sell',
            name='wood_id',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='lenn',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='rat',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='wid',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mill',
            name='mob',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sell',
            name='length',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sell',
            name='rate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sell',
            name='width',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user1',
            name='mob',
            field=models.BigIntegerField(),
        ),
    ]
