# Generated by Django 2.2.7 on 2020-04-11 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0022_auto_20200411_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='usell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('wood', models.CharField(max_length=100)),
                ('length', models.CharField(max_length=100)),
                ('width', models.CharField(max_length=100)),
                ('rate', models.CharField(max_length=100)),
            ],
        ),
    ]
