# Generated by Django 2.2.7 on 2020-04-20 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0024_usell_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='usell',
            name='umail',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
