# Generated by Django 2.2.7 on 2020-04-23 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0027_bank'),
    ]

    operations = [
        migrations.AddField(
            model_name='sell',
            name='user',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
