# Generated by Django 2.2.7 on 2020-04-23 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0028_sell_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sell',
            name='user',
        ),
    ]
