# Generated by Django 2.2.7 on 2020-04-24 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0030_auto_20200424_1055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='email',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='wood_id',
        ),
    ]
