# Generated by Django 2.2.7 on 2020-04-29 04:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0033_sell_usname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='wid',
            new_name='cir',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='uname',
            new_name='mname',
        ),
        migrations.AddField(
            model_name='booking',
            name='sitetime',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking',
            name='usname',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
