# Generated by Django 2.2.7 on 2020-04-29 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0034_auto_20200429_1019'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='sitetime',
            new_name='time',
        ),
        migrations.AddField(
            model_name='booking',
            name='sitedate',
            field=models.DateField(default=2),
            preserve_default=False,
        ),
    ]
