# Generated by Django 2.2.7 on 2020-04-29 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0035_auto_20200429_1020'),
    ]

    operations = [
        migrations.DeleteModel(
            name='booking',
        ),
    ]
