# Generated by Django 2.2.7 on 2020-04-29 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0036_delete_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='timber',
            name='ttype',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
