# Generated by Django 2.2.7 on 2020-04-29 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0037_timber_ttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timber',
            name='ttype',
        ),
    ]
