# Generated by Django 2.2.7 on 2020-04-29 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0038_remove_timber_ttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('usname', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=100)),
                ('mill_name', models.CharField(max_length=100)),
                ('type_wd', models.CharField(max_length=100)),
                ('lenn', models.CharField(max_length=100)),
                ('cir', models.CharField(max_length=100)),
                ('rat', models.CharField(max_length=100)),
            ],
        ),
    ]
