# Generated by Django 2.2.7 on 2020-04-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0039_booking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='booking',
            new_name='booking2',
        ),
    ]
