# Generated by Django 2.2.7 on 2020-04-29 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0040_auto_20200429_1454'),
    ]

    operations = [
        migrations.DeleteModel(
            name='booking2',
        ),
    ]
