# Generated by Django 2.2.7 on 2020-04-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0041_delete_booking2'),
    ]

    operations = [
        migrations.CreateModel(
            name='stvisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('usname', models.CharField(max_length=100)),
                ('mname', models.CharField(max_length=100)),
                ('mill_name', models.CharField(max_length=100)),
                ('type_wd', models.CharField(max_length=100)),
                ('lenn', models.IntegerField()),
                ('cir', models.IntegerField()),
                ('rat', models.IntegerField()),
                ('sdate', models.DateField()),
                ('stime', models.TextField()),
            ],
        ),
    ]
