# Generated by Django 2.2.7 on 2020-04-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0042_stvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stvisit',
            name='stime',
            field=models.CharField(max_length=100),
        ),
    ]
