# Generated by Django 2.2.7 on 2020-04-29 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0043_auto_20200429_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='stvisit',
            name='wid',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mill',
            name='mob',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='sell',
            name='length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sell',
            name='rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sell',
            name='width',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sell',
            name='wood_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usell',
            name='length',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usell',
            name='rate',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usell',
            name='width',
            field=models.IntegerField(),
        ),
    ]
