# Generated by Django 2.2.7 on 2020-04-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0044_auto_20200429_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stvisit',
            name='wid',
        ),
    ]
