# Generated by Django 2.2.7 on 2020-04-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0045_remove_stvisit_wid'),
    ]

    operations = [
        migrations.AddField(
            model_name='stvisit',
            name='wid',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
