# Generated by Django 2.2.7 on 2020-04-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0046_stvisit_wid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sell',
            name='length',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sell',
            name='rate',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sell',
            name='width',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='sell',
            name='wood_id',
            field=models.CharField(max_length=100),
        ),
    ]
