# Generated by Django 2.2.7 on 2020-04-30 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0047_auto_20200430_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='usell',
            name='mill',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usell',
            name='mname',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
