# Generated by Django 2.2.7 on 2020-05-02 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0049_auto_20200501_1013'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sdate', models.DateField()),
                ('stime', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='stvisit',
        ),
    ]
