# Generated by Django 2.2.7 on 2020-05-02 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0050_auto_20200502_0901'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='booking',
            new_name='book',
        ),
    ]
