# Generated by Django 2.2.7 on 2020-05-02 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0051_auto_20200502_0902'),
    ]

    operations = [
        migrations.DeleteModel(
            name='book',
        ),
    ]
