# Generated by Django 2.2.7 on 2020-05-02 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0053_stvisit'),
    ]

    operations = [
        migrations.DeleteModel(
            name='stvisit',
        ),
    ]
