# Generated by Django 2.2.7 on 2020-05-02 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0054_delete_stvisit'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank',
            name='status',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
