# Generated by Django 2.2.7 on 2020-05-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0055_bank_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='bdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
