# Generated by Django 2.2.7 on 2020-05-02 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0058_bkdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bkdetails',
            name='cirf',
        ),
        migrations.RemoveField(
            model_name='bkdetails',
            name='leng',
        ),
        migrations.RemoveField(
            model_name='bkdetails',
            name='memail',
        ),
        migrations.RemoveField(
            model_name='bkdetails',
            name='mill',
        ),
        migrations.RemoveField(
            model_name='bkdetails',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bkdetails',
            name='timber',
        ),
        migrations.RemoveField(
            model_name='bkdetails',
            name='uemail',
        ),
        migrations.RemoveField(
            model_name='bkdetails',
            name='user',
        ),
        migrations.RemoveField(
            model_name='bkdetails',
            name='wo_id',
        ),
    ]
