# Generated by Django 2.2.7 on 2020-05-02 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0059_auto_20200502_1247'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bkdetails',
        ),
    ]
