# Generated by Django 2.2.7 on 2020-05-02 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0060_delete_bkdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='bkdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_id', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=100)),
                ('uemail', models.CharField(max_length=100)),
                ('mill', models.CharField(max_length=100)),
                ('memail', models.CharField(max_length=100)),
                ('timber', models.CharField(max_length=100)),
                ('leng', models.CharField(max_length=100)),
                ('cirf', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('svdate', models.DateField()),
                ('svtime', models.TextField()),
            ],
        ),
    ]
