# Generated by Django 2.2.7 on 2020-05-09 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0062_usdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='premium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acno', models.IntegerField()),
                ('emon', models.CharField(max_length=100)),
                ('eyear', models.CharField(max_length=100)),
                ('cvv', models.IntegerField()),
            ],
        ),
    ]
