# Generated by Django 2.2.7 on 2020-05-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0063_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium',
            name='acno',
            field=models.CharField(max_length=100),
        ),
    ]
