# Generated by Django 2.2.7 on 2020-05-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0064_auto_20200509_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium',
            name='cvv',
            field=models.CharField(max_length=100),
        ),
    ]
