# Generated by Django 2.2.7 on 2020-05-09 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0065_auto_20200509_1810'),
    ]

    operations = [
        migrations.DeleteModel(
            name='premium',
        ),
    ]
