# Generated by Django 2.2.7 on 2020-05-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0067_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='cardno',
        ),
        migrations.AddField(
            model_name='membership',
            name='cno',
            field=models.BigIntegerField(default=2),
            preserve_default=False,
        ),
    ]
