# Generated by Django 2.2.7 on 2020-05-10 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0068_auto_20200509_2204'),
    ]

    operations = [
        migrations.DeleteModel(
            name='membership',
        ),
    ]
