# Generated by Django 2.2.7 on 2020-05-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0069_delete_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='premium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cno', models.BigIntegerField()),
                ('month', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('cvv', models.IntegerField()),
            ],
        ),
    ]
