# Generated by Django 2.2.7 on 2020-05-10 06:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0070_premium'),
    ]

    operations = [
        migrations.DeleteModel(
            name='premium',
        ),
        migrations.RenameField(
            model_name='timber',
            old_name='tname',
            new_name='month',
        ),
        migrations.AddField(
            model_name='timber',
            name='cno',
            field=models.BigIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timber',
            name='cvv',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='timber',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
