# Generated by Django 2.2.7 on 2020-05-10 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0071_auto_20200510_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='timber',
            name='status',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
