# Generated by Django 2.2.7 on 2020-05-10 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0072_timber_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timber',
            name='cvv',
            field=models.CharField(max_length=3),
        ),
    ]
